require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  DisplayCopNames: true
  Exclude:
    - "bin/**/*"
    - "db/schema.rb"
    - "node_modules/**/*"

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
    - "spec/factories.rb"

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Rails/BulkChangeTable:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - "spec/system/*"

RSpec/DescribedClass:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
