name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: db
          POSTGRES_USER: user
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - uses: actions/setup-node@v2-beta
      - run: bin/setup
        env:
          PGHOST: localhost
          PGUSER: user
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      - run: bundle exec rspec
        env:
          PGHOST: localhost
          PGUSER: user
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      - run: bin/lint
